### PR TITLE
Update build.gradle

### PR DESCRIPTION
**Pull request by wlr-branch**
updating Branch SDK 5.0.11 ->> 5.0.12 to include recent bug fixes.

### CODE REVIEW

**Comment by brandoFS** [comment]
hello, any ETA on getting this merged and deployed? this is a critical hotfix for my company. We are waiting for this fix to submit our app updates

**Comment by BrandonStalnaker** [comment]
@brandoFS Looking into this now. Thank you for calling this out.

**Comment by BrandonStalnaker** [comment]
Thank you for the commit @wlr-branch

**Comment by brandoFS** [comment]
thanks!

**Pull request merged**
