### PR TITLE
chore: bump Branch SDK version

### PR DESCRIPTION
**Pull request by nsingh-branch**
## Summary
Updated the Branch Android SDK's version from 5.2.7 to the latest, 5.10.1. 
The code updates were to the get() call and and update to use the BranchLogger class. Please let me know if there are any other changes required or if you need any more information from me.

It's important for us to get the update our quickly to give our clients access to the latest version of Branch.

 ## Testing Plan
 - [ ] Was this tested locally? If not, explain why.
- I was unable to get the provided SampleApplication to work

### CODE REVIEW

**Comment by nsingh-branch** [comment]
@samdozor @markvdouw Hi, just wanted to bump this PR for review.

**Comment by nsingh-branch** [comment]
Bumping this again @github-mparticle

**Comment by nsingh-branch** [comment]
> Hi @nsingh-branch - Mark is actually no longer with us, but we do have this on plate this sprint, and @Mansi-mParticle will be reviewing.

No problem, thank you!

**Review by Mansi-mParticle — APPROVED** [review]
Looks good to me

**Pull request merged**
